# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c96d3dc9c7f9169cdb4aede8a1b9bcee4cec7d7a765d5a025c4dd5a88c92ecc2b5095a550dab023a3c7408c98cb760df34b067efdadfda883d74299423626ea

test:
  secret_key_base: 56637b8de623844495f632745a32316e348f523efcf9f3bd5b06b735649f0ed42bab4fe5c985cf3588f7e1e16d6b5f8778071ee8326f26f6bd43f8a1ab53b415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
